window.digitalData = {
    versionDL: "unico",
    pageInstanceID: "",
    page: {
        pageInfo: {
            pageName: "",
            pageMode: "",
            pageIntent: "",
            pageSegment: "",
            sysEnv: "",
            version: "",
            channel: "",
            language: "",
            geoRegion: "",
            level1: "",
            level2: "",
            level3: "",
            level4: "",
            level5: "",
            level6: "",
            level7: "",
            level8: "",
            level9: "",
            level10: "",
            area: "",
            server: window.location.hostname,
            businessUnit: "",
            siteAppName: "",
            projectName: "",
            errorPage: "",
        },
        pageActivity: {
            search: {
                onSiteSearchResults: "",
                onSiteSearchTerm: "",
                onSiteSearchEnterTerm: "",
            },
            link: {
                name: "",
                url: "",
                ext: "",
                aux1: "",
                aux2: "",
                aux3: ""
            },
            video: {
                nameOfVideoDisplayed: "",
                duration: "",
                id: "",
                player: "",
                quality: "",
                url: "",
            },
            audio: {
                nameOfPodcastDisplayed: "",
                duration: "",
                id: "",
                player: "",
                quality: "",
                url: "",
            },
            loginType: "",
            loginError: "",
        },
    },
    optimization: {
            attributes: [{
                    idOptimization: "",
                    experience: "",
                    place: "",
                    type: "",
                    executor: "",
                    audience: "",
                }],
            event: {
                    eventName: "",
                    optimizationEvent: "",
 
                }
    },
    customerExperience: {
                attributes: [{
                    space: "",
                    spaceID: "",
                    spacePlacement: "",
                    collection: "",
                    collectionID: "",
                    collectionPosition: "",
                    collectionStatus: "",
                    collectionStatusTimeChange: "",
                    collectionType: "",
                    collectionExecutor: "",
                    item: "",
                    itemID: "",
                    itemPosition: "",
                    itemCategory: "",
                    itemStatus: "",
                    itemStatusTimeChange: "",
                    contractID: "",
                }],
                },
    internalCampaign: {
        attributes: [{
             location: "",
             campaignFormat: "",
             collectiveCode: "",
             campaignName: "",
             product: "",
             productCode: "",
             quantity: "",
         }],
         event: {
            eventInfo: {
                eventName: "",
                siteActionName: "",
            },
        },
    },
    user: {
        device: {
            userAgent: "",
            mobile: "",
            root: "",
            mode: "",  
            IPAddress: "",          
            advertisingID: "",
            usabilityMethod: "",
            signType: "",
            discreetMode: "",
            push:{
                agreement: "",
                deactivationPlace: "",
             },
            biometry:{
                agreement: "",
                deactivationPlace: "",
             },
        },
        consent:{
                    advertising: "",
                    analytics: "",
                    optimization: "",
                    version: "",
                    technique: ""
        },
        userScoring: "",
        userState: "",
        IDs: [{
               platformCode: "adobe",
               prospectID: "",
               profileID: "",
               affiliateCompanyID: "",
               userID: ""
             },
        ],
        e: "", 
        p: "", 
        gClientID: "",
        gSessionID: "",  
        mClientID: "", 
        secondaryCIF: "", 
        segment: {
            global: "",
            profile: "",
            collectiveID: "", 
            digitalizationLevel: "", 
            operativeArea: "", 
        },
        gender: "",
        country: "",
        state: "",
        age: "",
        civilStatus: "",
        educationLevel: "",
        jobType: "",
    },
    application: {
        transactionID: "",
        application: {
            type: "",
            name: "",
        },
        fulfillmentModel: "",
        typology: "",
        programTypeHired: "",
        offer: "",
        operationNumber: "",
        process: "",
        step: "",
        interactionLevel: "",
        isQualifiedVisits: "",
        isVerifiedIdentity: "",
        isActivatedProducts: "",
        state: "",
        errorType: "",
        earnings: "",
        expenses: "",
        customFields: "",
        globalApplication: "",
        declinedReason: "",
        reviewReason: "",
 
    },
    products: {
        attributes: [{
          primaryCategory: "",
             productSubtype: "",
             productName: "",
             productCode: "",
             contractID: "",
             quantity: "",
             amount: "",
             paymentAmount: "",
             numberOfPayments: "",
             paymentDate: "",
             paymentType: "",
             serviceCharge: "",
             currency: "",
             numberOfHolders: "",
             interestRate: {
               tin: "",
               tae: "",
               rate: "",
              },
             term: "",
             group: "",
             state: "",
        }
        ],
        productPortfolio: [{
             productName: "",
             balance: "",
             currency: "",
             productCode: "",   
        }],
    },
    activationTools: {
        adobeAnalytics: "",
        googleAnalytics: "",
        meta: "",
        googleAds: "",
        adServer: "",
        mobileAttribution: "",
        feedback: "",
    },
    news: {
         id: "",
         originalTitle: "",
         title: "",
         type: "",
         originalPublishDate: "",
         modifiedDate: "",
         country: "",
         category: "",
         signature: "",
         author: "",
         countryAuthor: "",
         relatedId: "",
         relatedOriginalTitle: "",
         relatedPosition: "",
         profile: {
              lifeCycle: "",
              value: "",
              behaviour: "",
         },
         product: "",
         channel: ""
     },
    formData:{
         name: "",
         surname: "",
         adress: "",
         jobtittle: ""
     }
 
 }
 
 